// Copyright (c) 2026 Omnodex, LLC. All rights reserved.
/**
 * Read model types. These are the projected shapes that the dashboard and
 * analyzer query against. They are derived from the event log and are
 * regenerated by replaying events through the projector.
 *
 * Keeping the read model types here (rather than in @omnodex/shared) is
 * deliberate. The event shapes are the wire format and must be stable;
 * the read model can change freely because it is always regenerable.
 */

import type { RiskSeverity } from "@omnodex/shared";

export interface SessionRow {
  session_id: string;
  user: string;
  project_path: string;
  mcp_servers: string[];
  started_at: string;
  ended_at: string | null;
  duration_ms: number | null;
  status: "in_progress" | "completed" | "errored" | "interrupted";
  tool_call_count: number;
  file_read_count: number;
  file_write_count: number;
  risk_score: number;
}

export interface ToolCallRow {
  tool_call_id: string;
  session_id: string;
  tool_name: string;
  mcp_server: string;
  parameters_json: string;
  started_at: string;
  ended_at: string | null;
  duration_ms: number | null;
  status: "in_progress" | "success" | "error";
  response_bytes: number | null;
  error_message: string | null;
}

export interface FileEventRow {
  session_id: string;
  direction: "read" | "write";
  path: string;
  bytes: number;
  at: string;
}

export interface RiskEventRow {
  session_id: string;
  related_event_id: string;
  severity: RiskSeverity;
  category: string;
  description: string;
  rule_id: string;
  detected_at: string;
}

/**
 * Storage interface for the read model. The projector drives this. The
 * Omnodex ships two implementations: an in-memory store (tests, default)
 * and a SQLite store (CLI, dashboard). Migrating to Postgres or any other
 * backend later is an implementation of this interface plus a constructor
 * swap in the CLI wiring.
 */
export interface ReadModelStore {
  /** Wipe everything. Used before a full replay. */
  reset(): Promise<void>;
  /** Called when a new session_id is first seen. */
  upsertSession(row: SessionRow): Promise<void>;
  /** Partial update keyed by session_id. */
  patchSession(
    sessionId: string,
    patch: Partial<Omit<SessionRow, "session_id">>,
  ): Promise<void>;
  incrementSessionCounter(
    sessionId: string,
    field: "tool_call_count" | "file_read_count" | "file_write_count",
    delta: number,
  ): Promise<void>;
  addToRiskScore(sessionId: string, delta: number): Promise<void>;
  /**
   * Add an MCP server name to the session's mcp_servers list if it is not
   * already present. No-op if the session does not exist or the server is
   * already recorded. Used by the projector to build the list from
   * tool.invoked events rather than relying on the SessionStart payload,
   * which Claude Code does not reliably populate.
   */
  addMcpServer(sessionId: string, mcpServer: string): Promise<void>;
  insertToolCall(row: ToolCallRow): Promise<void>;
  patchToolCall(
    toolCallId: string,
    patch: Partial<Omit<ToolCallRow, "tool_call_id" | "session_id">>,
  ): Promise<void>;
  insertFileEvent(row: FileEventRow): Promise<void>;
  insertRiskEvent(row: RiskEventRow): Promise<void>;
  /** Query helpers used by tests and the CLI demo output. */
  getSession(sessionId: string): Promise<SessionRow | null>;
  listSessions(): Promise<SessionRow[]>;
  listToolCalls(sessionId: string): Promise<ToolCallRow[]>;
  listFileEvents(sessionId: string): Promise<FileEventRow[]>;
  listRiskEvents(sessionId: string): Promise<RiskEventRow[]>;
  /** Best-effort close. Not all stores need it. */
  close(): Promise<void>;
}
