// Copyright (c) 2026 Omnodex, LLC. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-only
//
// This file is part of Omnodex, licensed under the GNU Affero General
// Public License v3.0. You may obtain a copy at https://omnodex.com/licensing
// A commercial license is available for use without copyleft obligations.
/**
 * Read model types. These are the projected shapes that the dashboard and
 * analyzer query against. They are derived from the event log and are
 * regenerated by replaying events through the projector.
 *
 * Keeping the read model types here (rather than in @omnodex/shared) is
 * deliberate. The event shapes are the wire format and must be stable;
 * the read model can change freely because it is always regenerable.
 */

import type { InterceptorKind, McpServerTransport, PlatformKind, RiskSeverity } from "@omnodex/shared";

export interface SessionRow {
  session_id: string;
  user: string;
  project_path: string;
  mcp_servers: string[];
  /** Which interceptor produced the session.started event. */
  interceptor: InterceptorKind;
  started_at: string;
  ended_at: string | null;
  duration_ms: number | null;
  status: "in_progress" | "completed" | "errored" | "interrupted";
  tool_call_count: number;
  file_read_count: number;
  file_write_count: number;
  risk_score: number;
  /** ISO 8601 timestamp of the most recent event in this session. */
  last_event_at: string;
  /** Root directory this session was read from (multi-root aggregation). */
  source_root: string | null;
  /**
   * Agent runtime the session ran in, when an interceptor recorded one:
   * from session.started, or from the first event that carries it when a
   * session has no start (cloud Cowork tasks may not send one). Null when
   * unknown; optional for rows projected before it existed.
   */
  platform?: PlatformKind | null;
  /**
   * How each MCP server is reached, as session.started recorded it (the MCP
   * proxy knows; hooks do not). Absent when nothing recorded it. Local only:
   * not part of the sync payload.
   */
  mcp_server_transports?: McpServerTransport[];
  /**
   * The MCP client a proxy session served, as the client named itself.
   * Absent for hook sessions and older rows. In the sync payload, for the
   * hosted dashboard's label fallback.
   */
  mcp_client_name?: string;
  /**
   * The session's title, from its latest session.renamed event: the name
   * the user gave it, or the one the agent runtime generated. Absent when
   * none was recorded. In the sync payload, for the hosted session list.
   */
  title?: string;
}

export interface ToolCallRow {
  tool_call_id: string;
  session_id: string;
  tool_name: string;
  mcp_server: string;
  /**
   * Which interceptor observed this call. Sessions carry one too, but a
   * correlated pair spans two sessions with different interceptors, so
   * consumers need it per row to label the sources of one logical call.
   * Optional for rows projected before it existed.
   */
  interceptor?: string;
  /**
   * Shared by the hook-observed and proxy-observed rows of a single call.
   * Null when a call was seen only once, which is every call that did not go
   * through the proxy. Set by a pass over the read model, never at write
   * time. See correlate.ts.
   */
  correlation_id?: string | null;
  parameters_json: string;
  started_at: string;
  ended_at: string | null;
  duration_ms: number | null;
  status: "in_progress" | "success" | "error";
  response_bytes: number | null;
  error_message: string | null;
  /**
   * The subagent that made the call, when it ran inside one. Absent for the
   * main agent and for rows projected before it existed.
   */
  agent_id?: string;
}

/** One prompt the user submitted, from a prompt.submitted event. */
export interface PromptRow {
  /** event_id of the prompt.submitted event; the row's natural key. */
  event_id: string;
  session_id: string;
  /** The full prompt text. */
  prompt: string;
  /** The runtime's id for the turn, when it sent one. */
  prompt_id?: string;
  at: string;
}

/**
 * One subagent, from its subagent.started and subagent.stopped events.
 * Keyed on session plus agent_id. Either event can arrive first or alone:
 * a dashboard opened mid-session, or a log that starts mid-way.
 */
export interface SubagentRow {
  session_id: string;
  agent_id: string;
  agent_type?: string;
  /** Null when only the stop was seen. */
  started_at: string | null;
  ended_at: string | null;
  duration_ms: number | null;
  status: "in_progress" | "completed" | "errored" | "interrupted";
  /** Size of the subagent's final message; the text is not recorded. */
  response_bytes: number | null;
}

export interface FileEventRow {
  /**
   * event_id of the originating file.read / file.written event. This is the
   * row's natural key: the same log event projected twice must not produce
   * two rows. Tool calls key on tool_call_id and sessions on session_id;
   * file events have no other stable identity.
   */
  event_id: string;
  session_id: string;
  direction: "read" | "write";
  path: string;
  bytes: number;
  at: string;
}

export interface RiskEventRow {
  /** event_id of the originating risk.detected event. */
  event_id: string;
  session_id: string;
  related_event_id: string;
  severity: RiskSeverity;
  category: string;
  description: string;
  rule_id: string;
  detected_at: string;
  /**
   * Set when the finding's tool call is one half of a correlated hook and
   * proxy pair: the pair's correlation_id. Both observations of a routed
   * call can raise the same finding; findingKey() counts them once.
   */
  correlation_id?: string | null;
  /** Tier of the rule that fired, when recorded. Absent reads as community. */
  rule_tier?: "community" | "advanced";
  /**
   * For a finding on a sequence of calls: every tool_call_id in the pattern,
   * earliest first. Absent for single-call findings. Local only: neither
   * this nor rule_tier is part of the sync payload.
   */
  related_event_ids?: string[];
}

/**
 * Identity of a finding for counting: rule plus the call it is about. The
 * hook's and the proxy's finding on one routed call share a correlation_id,
 * so they share a key; any other finding is keyed on its own session and
 * call.
 */
export function findingKey(row: Pick<RiskEventRow, "rule_id" | "session_id" | "related_event_id" | "correlation_id">): string {
  return row.correlation_id
    ? `${row.rule_id}::corr:${row.correlation_id}`
    : `${row.rule_id}::${row.session_id}::${row.related_event_id}`;
}

/**
 * Storage interface for the read model. The projector drives this. The
 * Omnodex ships two implementations: an in-memory store (tests, default)
 * and a SQLite store (CLI, dashboard). Migrating to Postgres or any other
 * backend later is an implementation of this interface plus a constructor
 * swap in the CLI wiring.
 */
export interface ReadModelStore {
  /** Wipe everything. Used before a full replay. */
  reset(): Promise<void>;
  /** Called when a new session_id is first seen. */
  upsertSession(row: SessionRow): Promise<void>;
  /** Partial update keyed by session_id. */
  patchSession(
    sessionId: string,
    patch: Partial<Omit<SessionRow, "session_id">>,
  ): Promise<void>;
  incrementSessionCounter(
    sessionId: string,
    field: "tool_call_count" | "file_read_count" | "file_write_count",
    delta: number,
  ): Promise<void>;
  addToRiskScore(sessionId: string, delta: number): Promise<void>;
  /**
   * Add an MCP server name to the session's mcp_servers list if it is not
   * already present. No-op if the session does not exist or the server is
   * already recorded. Used by the projector to build the list from
   * tool.invoked events rather than relying on the SessionStart payload,
   * which Claude Code does not reliably populate.
   */
  addMcpServer(sessionId: string, mcpServer: string): Promise<void>;
  /**
   * Insert a tool call, keyed on tool_call_id.
   *
   * Returns true when a row was written and false when one already existed.
   * The projector uses the answer to decide whether to move the session's
   * counters, which is what keeps a replayed or duplicated event from
   * inflating them: the row is suppressed and the count must be too.
   * The same contract applies to insertFileEvent and insertRiskEvent.
   */
  insertToolCall(row: ToolCallRow): Promise<boolean>;
  patchToolCall(
    toolCallId: string,
    patch: Partial<Omit<ToolCallRow, "tool_call_id" | "session_id">>,
  ): Promise<void>;
  /** Insert a file event, keyed on event_id. Returns false if already present. */
  insertFileEvent(row: FileEventRow): Promise<boolean>;
  /** Insert a prompt, keyed on event_id. Returns false if already present. */
  insertPrompt(row: PromptRow): Promise<boolean>;
  /**
   * Create or update a subagent, keyed on session_id + agent_id. A new row
   * starts from `patch` over an in-progress default; an existing row takes
   * the defined fields of `patch`, so a late start does not undo a stop.
   */
  upsertSubagent(
    sessionId: string,
    agentId: string,
    patch: Partial<Omit<SubagentRow, "session_id" | "agent_id">>,
  ): Promise<void>;
  /**
   * Insert a risk event, keyed on session_id + rule_id + related_event_id
   * rather than event_id. Two analyzer runs over the same tool call mint
   * different event_ids for the same finding, and this is the key detect.ts
   * and the hosted dashboard's reducer already dedup on. Returns false if
   * the finding is already recorded.
   */
  insertRiskEvent(row: RiskEventRow): Promise<boolean>;
  /**
   * Mark every finding about any of the given tool calls with a
   * correlation_id. Returns how many rows changed.
   */
  setRiskCorrelation(relatedEventIds: readonly string[], correlationId: string): Promise<number>;
  /** Query helpers used by tests and the CLI demo output. */
  getSession(sessionId: string): Promise<SessionRow | null>;
  listSessions(): Promise<SessionRow[]>;
  listToolCalls(sessionId: string): Promise<ToolCallRow[]>;
  /**
   * Every tool call in the store, across all sessions. Correlation needs a
   * whole-model view because a hook call and its proxy counterpart live in
   * different sessions.
   */
  listAllToolCalls(): Promise<ToolCallRow[]>;
  listFileEvents(sessionId: string): Promise<FileEventRow[]>;
  listRiskEvents(sessionId: string): Promise<RiskEventRow[]>;
  /** The session's prompts, oldest first. */
  listPrompts(sessionId: string): Promise<PromptRow[]>;
  /** The session's subagents, by start time (rows without one last). */
  listSubagents(sessionId: string): Promise<SubagentRow[]>;
  /** Best-effort close. Not all stores need it. */
  close(): Promise<void>;
}
