// Copyright (c) 2026 Omnodex, LLC. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-only
//
// This file is part of Omnodex, licensed under the GNU Affero General
// Public License v3.0. You may obtain a copy at https://omnodex.com/licensing
// A commercial license is available for use without copyleft obligations.
/**
 * launcher-template.ts
 *
 * Generates stable hook launcher scripts that live at ~/.omnodex/bin/.
 * These launchers resolve the actual hook shim at runtime by searching
 * npm global dirs, config overrides, and env vars. Because the launcher
 * path never changes, hook commands embedded in project settings survive
 * npm updates without re-running `omnodex install`.
 *
 * Resolution order (mirrors launch-proxy.js):
 *   1. OMNODEX_SHIM_PATH env var (explicit override)
 *   2. shim_paths.<platform> in ~/.omnodex/omnodex-config.json
 *   3. omnodex on PATH -> resolve relative to its location
 *   4. Common global npm node_modules dirs
 *   5. require.resolve from the Node binary running the launcher
 *
 * Steps 3-5 check two layouts: a workspace checkout
 * (packages/<provider>/dist/bin/<shim>) and the published npm package,
 * which ships every shim flat in its bin/ directory (omnodex/bin/<shim>).
 *
 * Arguments passed to the launcher are forwarded to the shim (Antigravity
 * passes the hook event name this way). Setting OMNODEX_LAUNCHER_RESOLVE_ONLY=1
 * prints the resolved shim path and exits without running it, which is how
 * `omnodex status` checks that hooks can find their shim.
 */

import { promises as fs } from "node:fs";
import { spawnSync } from "node:child_process";
import * as path from "node:path";
import * as os from "node:os";

export type LauncherPlatform = "claude-code" | "codex" | "antigravity";

interface PlatformShimInfo {
  /** npm package name under @omnodex/ */
  packageName: string;
  /** Path within the package to the shim script (from package root) */
  shimRelative: string;
  /** Launcher filename written to ~/.omnodex/bin/ */
  launcherFilename: string;
}

const PLATFORM_INFO: Record<LauncherPlatform, PlatformShimInfo> = {
  "claude-code": {
    packageName: "hooks-provider",
    shimRelative: "dist/bin/claude-hook-shim.js",
    launcherFilename: "claude-hook-launcher.js",
  },
  codex: {
    packageName: "codex-provider",
    shimRelative: "dist/bin/codex-hook-shim.js",
    launcherFilename: "codex-hook-launcher.js",
  },
  antigravity: {
    packageName: "antigravity-provider",
    shimRelative: "dist/bin/antigravity-hook-shim.js",
    launcherFilename: "antigravity-hook-launcher.js",
  },
};

/** All platforms that have a hook launcher. */
export const LAUNCHER_PLATFORMS: LauncherPlatform[] = ["claude-code", "codex", "antigravity"];

/**
 * Filename of a platform's shim. The published npm package ships each shim
 * under this name in its bin/ directory.
 */
export function shimFilename(platform: LauncherPlatform): string {
  return path.posix.basename(PLATFORM_INFO[platform].shimRelative);
}

/**
 * Return the stable path where a launcher will be written.
 * Does not check whether the file exists.
 */
export function launcherPath(platform: LauncherPlatform): string {
  const info = PLATFORM_INFO[platform];
  return path.join(os.homedir(), ".omnodex", "bin", info.launcherFilename);
}

/**
 * Generate the JavaScript source for a platform-specific hook launcher.
 * The generated script is a standalone CJS file with no dependencies.
 * Uses string concatenation to avoid nested template literal escaping.
 */
export function generateLauncherSource(platform: LauncherPlatform): string {
  const info = PLATFORM_INFO[platform];
  const lines: string[] = [
    '#!/usr/bin/env node',
    '// Omnodex stable hook launcher - ' + platform,
    '// Generated by `omnodex install`. Do not edit manually.',
    '// This file survives npm updates. The actual hook shim is resolved at runtime.',
    '"use strict";',
    'const { spawnSync } = require("node:child_process");',
    'const { existsSync, readFileSync, realpathSync, mkdirSync, appendFileSync } = require("node:fs");',
    'const { join, dirname } = require("node:path");',
    'const os = require("node:os");',
    '',
    'const PLATFORM = ' + JSON.stringify(platform) + ';',
    'const PACKAGE_NAME = ' + JSON.stringify(info.packageName) + ';',
    'const SHIM_RELATIVE = ' + JSON.stringify(info.shimRelative) + ';',
    'const SHIM_FILE = ' + JSON.stringify(shimFilename(platform)) + ';',
    '',
    'const HOME = os.homedir();',
    'const OMNODEX_DIR = process.env.OMNODEX_HOME || join(HOME, ".omnodex");',
    'const DEBUG = process.env.OMNODEX_DEBUG === "1";',
    'const LOG_PATH = join(OMNODEX_DIR, "launcher.log");',
    '',
    'function log(msg) {',
    '  if (!DEBUG) return;',
    '  var line = "[" + new Date().toISOString() + "] [" + PLATFORM + "] " + msg + "\\n";',
    '  process.stderr.write(line);',
    '  try {',
    '    mkdirSync(OMNODEX_DIR, { recursive: true });',
    '    appendFileSync(LOG_PATH, line);',
    '  } catch (e) {}',
    '}',
    '',
    'function logFatal(msg) {',
    '  var line = "[omnodex] " + msg + "\\n";',
    '  process.stderr.write(line);',
    '  try {',
    '    mkdirSync(OMNODEX_DIR, { recursive: true });',
    '    appendFileSync(LOG_PATH, "[" + new Date().toISOString() + "] FATAL [" + PLATFORM + "] " + msg + "\\n");',
    '  } catch (e) {}',
    '}',
    '',
    'function findShim() {',
    '  // 1. Explicit env var override',
    '  if (process.env.OMNODEX_SHIM_PATH) {',
    '    log("using OMNODEX_SHIM_PATH = " + process.env.OMNODEX_SHIM_PATH);',
    '    return process.env.OMNODEX_SHIM_PATH;',
    '  }',
    '',
    '  // 2. Config file override (survives env-stripping hosts like Cowork)',
    '  try {',
    '    var configPath = join(OMNODEX_DIR, "omnodex-config.json");',
    '    var raw = readFileSync(configPath, "utf8");',
    '    var cfg = JSON.parse(raw);',
    '    if (cfg.shim_paths && cfg.shim_paths[PLATFORM]) {',
    '      var p = cfg.shim_paths[PLATFORM];',
    '      if (existsSync(p)) {',
    '        log("using shim_paths." + PLATFORM + " from config: " + p);',
    '        return p;',
    '      }',
    '      log("shim_paths." + PLATFORM + " in config not found: " + p);',
    '    }',
    '  } catch (e) {}',
    '',
    '  // 3. Check PATH for omnodex binary -> resolve relative to it',
    '  var isWindows = process.platform === "win32";',
    '  try {',
    '    var result = spawnSync(',
    '      isWindows ? "where" : "which",',
    '      ["omnodex"],',
    '      { encoding: "utf8", timeout: 5000 }',
    '    );',
    '    if (result.status === 0 && result.stdout.trim()) {',
    '      var omnodexBin = result.stdout.trim().split(/\\r?\\n/)[0].trim();',
    '      // npm package: bin/omnodex is symlinked into the global bin dir on Unix',
    '      try {',
    '        var sibling = join(dirname(realpathSync(omnodexBin)), SHIM_FILE);',
    '        if (existsSync(sibling)) {',
    '          log("found next to PATH omnodex binary: " + sibling);',
    '          return sibling;',
    '        }',
    '      } catch (e) {}',
    '      var dir = dirname(omnodexBin);',
    '      for (var i = 0; i < 8; i++) {',
    '        var candidate = join(dir, "packages", PACKAGE_NAME, SHIM_RELATIVE);',
    '        if (existsSync(candidate)) {',
    '          log("found via PATH omnodex binary: " + candidate);',
    '          return candidate;',
    '        }',
    '        var parentCandidate = join(dir, "node_modules", "@omnodex", PACKAGE_NAME, SHIM_RELATIVE);',
    '        if (existsSync(parentCandidate)) {',
    '          log("found via PATH node_modules: " + parentCandidate);',
    '          return parentCandidate;',
    '        }',
    '        // npm package: Windows wrappers sit beside node_modules/omnodex',
    '        var packageCandidate = join(dir, "node_modules", "omnodex", "bin", SHIM_FILE);',
    '        if (existsSync(packageCandidate)) {',
    '          log("found via PATH omnodex package: " + packageCandidate);',
    '          return packageCandidate;',
    '        }',
    '        dir = dirname(dir);',
    '      }',
    '    }',
    '  } catch (e) {}',
    '',
    '  // 4. Common global npm node_modules locations',
    '  var nodeDir = dirname(process.execPath);',
    '  var candidates = [',
    '    // Monorepo layout under npm global (workspace install)',
    '    join(HOME, ".npm-global", "lib", "node_modules", "omnodex", "packages", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join("/usr", "local", "lib", "node_modules", "omnodex", "packages", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join("/usr", "lib", "node_modules", "omnodex", "packages", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join("/opt", "homebrew", "lib", "node_modules", "omnodex", "packages", PACKAGE_NAME, SHIM_RELATIVE),',
    '    // Scoped package layout',
    '    join(HOME, ".npm-global", "lib", "node_modules", "@omnodex", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join("/usr", "local", "lib", "node_modules", "@omnodex", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join("/usr", "lib", "node_modules", "@omnodex", PACKAGE_NAME, SHIM_RELATIVE),',
    '    // Windows',
    '    join(HOME, "AppData", "Roaming", "npm", "node_modules", "omnodex", "packages", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join(HOME, "AppData", "Roaming", "npm", "node_modules", "@omnodex", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join(nodeDir, "node_modules", "omnodex", "packages", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join(nodeDir, "node_modules", "@omnodex", PACKAGE_NAME, SHIM_RELATIVE),',
    '    // nvm / fnm / volta',
    '    join(dirname(nodeDir), "lib", "node_modules", "omnodex", "packages", PACKAGE_NAME, SHIM_RELATIVE),',
    '    join(dirname(nodeDir), "lib", "node_modules", "@omnodex", PACKAGE_NAME, SHIM_RELATIVE),',
    '    // Published npm package (shims ship flat in omnodex/bin)',
    '    join(dirname(nodeDir), "lib", "node_modules", "omnodex", "bin", SHIM_FILE),',
    '    join(nodeDir, "node_modules", "omnodex", "bin", SHIM_FILE),',
    '    join(HOME, ".npm-global", "lib", "node_modules", "omnodex", "bin", SHIM_FILE),',
    '    join("/usr", "local", "lib", "node_modules", "omnodex", "bin", SHIM_FILE),',
    '    join("/usr", "lib", "node_modules", "omnodex", "bin", SHIM_FILE),',
    '    join("/opt", "homebrew", "lib", "node_modules", "omnodex", "bin", SHIM_FILE),',
    '    join(HOME, "AppData", "Roaming", "npm", "node_modules", "omnodex", "bin", SHIM_FILE),',
    '  ];',
    '  for (var ci = 0; ci < candidates.length; ci++) {',
    '    if (existsSync(candidates[ci])) {',
    '      log("found via candidate list: " + candidates[ci]);',
    '      return candidates[ci];',
    '    }',
    '  }',
    '',
    '  // 5. Try require.resolve',
    '  try {',
    '    var resolveScript = "try { console.log(require.resolve(\\"@omnodex/" + PACKAGE_NAME + "/" + SHIM_RELATIVE + "\\")); } catch (e) { try { console.log(require.resolve(\\"omnodex/packages/" + PACKAGE_NAME + "/" + SHIM_RELATIVE + "\\")); } catch (e2) { try { console.log(require.resolve(\\"omnodex/bin/" + SHIM_FILE + "\\")); } catch (e3) {} } }";',
    '    var result2 = spawnSync(',
    '      process.execPath,',
    '      ["-e", resolveScript],',
    '      { encoding: "utf8", timeout: 5000 }',
    '    );',
    '    if (result2.status === 0 && result2.stdout.trim()) {',
    '      var resolved = result2.stdout.trim();',
    '      if (existsSync(resolved)) {',
    '        log("found via require.resolve: " + resolved);',
    '        return resolved;',
    '      }',
    '    }',
    '  } catch (e) {}',
    '',
    '  log("shim not found by any method");',
    '  return null;',
    '}',
    '',
    'log("launcher started");',
    'var shimPath = findShim();',
    '',
    '// Resolve-only mode: report the shim path without running it',
    'if (process.env.OMNODEX_LAUNCHER_RESOLVE_ONLY === "1") {',
    '  if (shimPath) process.stdout.write(shimPath + "\\n");',
    '  process.exit(shimPath ? 0 : 1);',
    '}',
    '',
    'if (!shimPath) {',
    '  logFatal("Could not locate " + PLATFORM + " hook shim. Run: omnodex status");',
    '  // Exit 0 so the AI agent is never blocked by a missing Omnodex install',
    '  process.exit(0);',
    '}',
    '',
    'log("spawning shim: " + shimPath);',
    'var result = spawnSync(process.execPath, [shimPath].concat(process.argv.slice(2)), {',
    '  stdio: "inherit",',
    '  env: process.env,',
    '});',
    '',
    'if (result.error) {',
    '  logFatal("Failed to spawn shim: " + result.error.message);',
    '  process.exit(0);',
    '}',
    '',
    'process.exit(result.status || 0);',
  ];
  return lines.join("\n") + "\n";
}

/**
 * Write (or refresh) the stable launcher for a given platform.
 * Creates ~/.omnodex/bin/ if it doesn't exist.
 * Returns the absolute path to the written launcher.
 */
export async function writeLauncher(platform: LauncherPlatform): Promise<string> {
  const dest = launcherPath(platform);
  const dir = path.dirname(dest);
  await fs.mkdir(dir, { recursive: true });
  const source = generateLauncherSource(platform);
  await fs.writeFile(dest, source, { mode: 0o755 });
  return dest;
}

/**
 * Write (or refresh) launchers for all platforms.
 * Returns a map of platform -> launcher path.
 */
export async function writeAllLaunchers(): Promise<Record<LauncherPlatform, string>> {
  const result = {} as Record<LauncherPlatform, string>;
  for (const p of LAUNCHER_PLATFORMS) {
    result[p] = await writeLauncher(p);
  }
  return result;
}

/**
 * Rewrite launchers that exist but were generated by a different version.
 * Launchers that were never installed are left alone. Returns the platforms
 * that were refreshed.
 *
 * `omnodex update` refreshes launchers from the process that ran the npm
 * install, which is still the old version, so the new version calls this on
 * startup to replace them.
 */
export async function refreshStaleLaunchers(): Promise<LauncherPlatform[]> {
  const refreshed: LauncherPlatform[] = [];
  for (const p of LAUNCHER_PLATFORMS) {
    try {
      await fs.access(launcherPath(p));
    } catch {
      continue;
    }
    if (!(await isLauncherCurrent(p))) {
      await writeLauncher(p);
      refreshed.push(p);
    }
  }
  return refreshed;
}

/**
 * Run a launcher in resolve-only mode and return the shim path it finds,
 * or null if it cannot locate one.
 */
export function resolveLauncherShim(platform: LauncherPlatform): string | null {
  const result = spawnSync(process.execPath, [launcherPath(platform)], {
    encoding: "utf8",
    env: { ...process.env, OMNODEX_LAUNCHER_RESOLVE_ONLY: "1" },
    timeout: 15000,
  });
  const out = result.status === 0 ? result.stdout.trim() : "";
  return out || null;
}

/**
 * Check whether a launcher exists and is up to date.
 * Compares the first line (shebang) and the PLATFORM constant to detect
 * launchers that need refreshing (e.g. after format changes).
 */
export async function isLauncherCurrent(platform: LauncherPlatform): Promise<boolean> {
  const dest = launcherPath(platform);
  try {
    const existing = await fs.readFile(dest, "utf8");
    const expected = generateLauncherSource(platform);
    // Compare just the functional parts (skip timestamps/comments that might differ)
    return existing === expected;
  } catch {
    return false;
  }
}
