// Copyright (c) 2026 Omnodex, LLC. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-only
//
// This file is part of Omnodex, licensed under the GNU Affero General
// Public License v3.0. You may obtain a copy at https://omnodex.com/licensing
// A commercial license is available for use without copyleft obligations.
/**
 * Streaming detect loop.
 *
 * Tails the event log for each active session, projects new events into
 * the SQLite read model, runs the rule engine against tool.invoked events
 * in real time, appends any new risk.detected events back to the log, and
 * broadcasts projected row updates to all connected SSE clients.
 *
 * This replaces the batch detect-then-replay approach used by the
 * earlier batch-only dashboard command. The batch approach still runs once
 * on startup to process any historical sessions that completed before the
 * dashboard was opened.
 *
 * Key design choices:
 *   - Per-session deduplication is maintained in memory (processedIds set).
 *     We pre-seed it from the existing session log on startup so historical
 *     events are never re-projected or re-detected.
 *   - Risk events generated by the streaming loop are pre-registered in the
 *     processedIds set before being appended to the event log, so the tail
 *     loop does not double-process them when it reads them back.
 *   - broadcastProjection fetches updated rows from the store after each
 *     apply() call. This keeps the SSE payload identical to what the REST
 *     API would return, ensuring the dashboard's state is always consistent.
 */

import { EventLog, newEventId } from "@omnodex/event-log";
import { Projector } from "@omnodex/projection";
import type { ReadModelStore } from "@omnodex/projection";
import { RuleEngine, RuleRegistry } from "@omnodex/analyzer";
import type { RiskDetectedEvent, TraceEvent } from "@omnodex/shared";
import { SCHEMA_VERSION } from "@omnodex/shared";
import type { DashboardServer } from "./dashboard-server.js";
import type { StreamingTransport } from "@omnodex/sync-encryptor";

// ---------------------------------------------------------------------------
// broadcastProjection
// ---------------------------------------------------------------------------

/**
 * After a single event has been applied to the read model, determine which
 * rows changed and push them to all connected SSE clients.
 *
 * Exported for unit testing.
 */
export async function broadcastProjection(
  event: TraceEvent,
  store: ReadModelStore,
  server: DashboardServer,
): Promise<void> {
  switch (event.event_type) {
    case "session.started":
    case "session.ended": {
      const row = await store.getSession(event.session_id);
      if (row) server.broadcast({ type: "session.upserted", payload: row });
      break;
    }

    case "tool.invoked": {
      // Broadcast the newly inserted tool call row.
      const calls = await store.listToolCalls(event.session_id);
      const row = calls.find((tc) => tc.tool_call_id === event.tool_call_id);
      if (row) server.broadcast({ type: "tool_call.inserted", payload: row });
      // Also refresh the session row -- tool_call_count and mcp_servers changed.
      const session = await store.getSession(event.session_id);
      if (session) server.broadcast({ type: "session.upserted", payload: session });
      break;
    }

    case "tool.completed": {
      const calls = await store.listToolCalls(event.session_id);
      const row = calls.find((tc) => tc.tool_call_id === event.tool_call_id);
      if (row) server.broadcast({ type: "tool_call.patched", payload: row });
      break;
    }

    case "file.read":
    case "file.written": {
      const events = await store.listFileEvents(event.session_id);
      const row = events[events.length - 1];
      if (row) server.broadcast({ type: "file_event.inserted", payload: row });
      // Refresh session -- file_read_count or file_write_count changed.
      const session = await store.getSession(event.session_id);
      if (session) server.broadcast({ type: "session.upserted", payload: session });
      break;
    }

    case "risk.detected": {
      const risks = await store.listRiskEvents(event.session_id);
      const row = risks.find(
        (r) =>
          r.related_event_id === event.related_event_id &&
          r.rule_id === event.rule_id,
      );
      if (row) server.broadcast({ type: "risk_event.inserted", payload: row });
      // Refresh session -- risk_score changed.
      const session = await store.getSession(event.session_id);
      if (session) server.broadcast({ type: "session.upserted", payload: session });
      break;
    }
  }
}

// ---------------------------------------------------------------------------
// tailSession
// ---------------------------------------------------------------------------

/**
 * Tail a single session's event log file, projecting events and running
 * detection in real time. Runs until `outerSignal` is aborted.
 *
 * @param replayHistory - When true, project the session's existing events
 *   before entering the tail loop. Pass true for sessions that appeared after
 *   the initial startup replay (i.e. detected by the poll loop), and false for
 *   sessions already covered by cmdDashboard's replay pass.
 *
 * Exported for unit testing.
 */
export async function tailSession(
  sessionId: string,
  log: EventLog,
  store: ReadModelStore,
  projector: Projector,
  server: DashboardServer,
  engine: RuleEngine,
  outerSignal: AbortSignal,
  replayHistory = false,
  sourceRoot: string | null = null,
  cloudTransport: StreamingTransport | null = null,
): Promise<void> {
  // Create a child AbortController so we can stop the tail when the outer
  // signal fires.
  const ctrl = new AbortController();
  const onAbort = (): void => ctrl.abort();
  if (outerSignal.aborted) {
    ctrl.abort();
  } else {
    outerSignal.addEventListener("abort", onAbort, { once: true });
  }

  try {
    // Read the session's existing events for two purposes:
    //   1. Pre-seed processedIds so the tail loop never re-projects them.
    //   2. If replayHistory is true (session appeared after the startup replay),
    //      project them now so the read model has a consistent baseline before
    //      we process any new events. Without this, a session.started event
    //      would be skipped and a subsequent risk.detected event would fail the
    //      FOREIGN KEY constraint on the sessions table.
    const existing = await log.readSession(sessionId);
    const processedIds = new Set<string>(existing.map((e) => e.event_id));
    const detectedKeys = new Set<string>(
      existing
        .filter((e): e is RiskDetectedEvent => e.event_type === "risk.detected")
        .map((e) => `${e.rule_id}::${e.related_event_id}`),
    );

    // Tell the projector which root these events come from.
    projector.setSourceRoot(sourceRoot);

    if (replayHistory) {
      for (const event of existing) {
        await projector.apply(event);
      }
    }

    for await (const event of log.tail(sessionId, ctrl.signal)) {
      if (processedIds.has(event.event_id)) continue;
      processedIds.add(event.event_id);

      // Project the event into the read model and broadcast the update.
      await projector.apply(event);
      await broadcastProjection(event, store, server);
      cloudTransport?.push(event).catch(() => {}); // fire-and-forget

      // Detection: only tool.invoked events carry the parameter data that
      // the rule conditions operate on.
      if (event.event_type === "tool.invoked") {
        const findings = engine.evaluate(event);

        for (const finding of findings) {
          const key = `${finding.rule_id}::${event.tool_call_id}`;
          if (detectedKeys.has(key)) continue;
          detectedKeys.add(key);

          const now = new Date().toISOString();
          const riskEvent: RiskDetectedEvent = {
            schema_version: SCHEMA_VERSION,
            event_id: newEventId(),
            session_id: event.session_id,
            occurred_at: now,
            recorded_at: now,
            interceptor: "analyzer",
            event_type: "risk.detected",
            severity: finding.severity,
            category: finding.category,
            description: finding.description,
            related_event_id: event.tool_call_id,
            rule_id: finding.rule_id,
          };

          // Pre-register the event_id so the tail loop does not re-process
          // this risk event when it reads the appended line back from disk.
          processedIds.add(riskEvent.event_id);

          await log.append(riskEvent);
          await projector.apply(riskEvent);
          await broadcastProjection(riskEvent, store, server);
          cloudTransport?.push(riskEvent).catch(() => {}); // fire-and-forget
        }
      }
    }
  } finally {
    outerSignal.removeEventListener("abort", onAbort);
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** A root the streaming loop should tail. */
export interface StreamingRoot {
  /** Absolute path to the OMNODEX_HOME root (used for labeling/filtering). */
  rootPath: string;
  /** EventLog instance for this root. */
  log: EventLog;
}

// ---------------------------------------------------------------------------
// startStreamingLoop
// ---------------------------------------------------------------------------

/**
 * Start the streaming detect loop.
 *
 * Accepts one or more roots. For each root, immediately kicks off a
 * tailSession() for each session that already exists in the event log
 * (with processedIds pre-seeded so nothing gets re-projected). Then polls
 * each root's session index every second for newly registered sessions
 * and starts tailing them as they appear.
 *
 * Returns a stop() function that aborts all tails and cleans up.
 *
 * **Backwards compatible:** passing a single EventLog still works via the
 * legacy overload.
 */
export function startStreamingLoop(
  logOrRoots: EventLog | StreamingRoot[],
  store: ReadModelStore,
  projector: Projector,
  server: DashboardServer,
  cloudTransport: StreamingTransport | null = null,
): { stop: () => void } {
  // Normalise: single EventLog → one-element roots array.
  const roots: StreamingRoot[] = Array.isArray(logOrRoots)
    ? logOrRoots
    : [{ rootPath: "", log: logOrRoots }];

  const ctrl = new AbortController();
  const activeSessions = new Set<string>();
  const registry = new RuleRegistry();
  const engine = new RuleEngine(registry.getRules());

  function launchTail(
    sessionId: string,
    log: EventLog,
    rootPath: string,
    replayHistory = false,
  ): void {
    // Key by root+session to avoid collisions across roots with same session id.
    const key = `${rootPath}::${sessionId}`;
    if (activeSessions.has(key)) return;
    activeSessions.add(key);

    // Tell the projector which root this session belongs to.
    // NOTE: setSourceRoot is per-apply, but since tailSession is per-session
    // and each session belongs to exactly one root, we set it before launching.
    // The projector's sourceRoot is set before each apply inside tailSession.
    tailSession(sessionId, log, store, projector, server, engine, ctrl.signal, replayHistory, rootPath, cloudTransport).catch(
      (err: unknown) => {
        console.error(`[stream] tail error for ${sessionId} (${rootPath}):`, err);
      },
    );
  }

  async function pollForRoot(root: StreamingRoot): Promise<void> {
    const { rootPath, log } = root;

    // Seed the initial set of sessions (already replayed by cmdDashboard).
    try {
      for (const sessionId of await log.listSessions()) {
        launchTail(sessionId, log, rootPath);
      }
    } catch {
      // Root may not exist yet -- keep polling.
    }

    while (!ctrl.signal.aborted) {
      await sleep(1_000);
      if (ctrl.signal.aborted) break;
      try {
        for (const sessionId of await log.listSessions()) {
          const key = `${rootPath}::${sessionId}`;
          if (!activeSessions.has(key)) {
            console.log(`[stream] new session detected: ${sessionId} (${rootPath})`);
            launchTail(sessionId, log, rootPath, true);
          }
        }
      } catch {
        // Transient read error on the index -- keep polling.
      }
    }
  }

  // Launch a poll loop per root. Fire and forget; errors are logged inside.
  for (const root of roots) {
    pollForRoot(root).catch((err: unknown) => {
      console.error(`[stream] session poll error for ${root.rootPath}:`, err);
    });
  }

  return {
    stop: (): void => {
      ctrl.abort();
    },
  };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function sleep(ms: number): Promise<void> {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
